### ISSUE TITLE
Bring back the Main Menu

### ISSUE THREAD

**Issue by P9Q** [bashor/IdeaMainMenuToggler#8]
My main menu's gone and I don't know how to toggle it now, Which keyboard shortcut shows(toggles) the Main Menu?

**Comment by bashor** [comment]
@P9Q find "Toggle Main Menu" action using "Find Everywhere" (Shift+Shift) and call it

**Comment by bashor** [comment]
It doesn't have a shortcut by default, but you can assign a shortcut in settings (find "Toggle Main Menu").

**Comment by P9Q** [comment]
@bashor, Thank you for your great plugin 👍 
apparently, Alt+D does nothing in phpstorm :expressionless: I chose this shortcut for toggling "Toggle Main Menu"
